name: Flutter CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
      - pruebas
      - test
      - release/*
  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch: # Activación manual opcional

jobs:
  build:
    name: Build and Test Flutter MEF
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Configurar Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    # 3. Cachear las dependencias de Flutter
    - name: Cache Flutter Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-
    
    # 4. Verify Flutter installation
    - name: Flutter Doctor
      run: flutter doctor

    # 5. Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # 6. Generar mocks (si es necesario)
    - name: Generate mocks
      run: flutter pub run build_runner build --delete-conflicting-outputs

    # 7. Ejecutar pruebas específicas
    - name: Run Tests
      run: flutter test test/services/url_service_test.dart  
  
    # 8. Instalar Java 17 (requiere Java 17 para la compilación)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 9. Establecer JAVA_HOME a la ubicación de Java 17
    - name: Set JAVA_HOME for Gradle
      run: |
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "Path to JAVA_HOME: $JAVA_HOME"

    # 10. Compilar la aplicación Flutter (APK)
    - name: Build Flutter APK
      run: flutter build apk --release
      continue-on-error: true 

    # 11. Subir el APK como artefacto
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    
  deploy:
    name: Deploy Flutter App
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    steps:
      # Checkout code from GitHub
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Clona todo el historial del repositorio

      # Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # Run Deployment Script (cambia este paso según tu proceso de despliegue)
      - name: Deploy Application
        run: echo "Desplegando la aplicación..."  # Aquí se debería colocar el script o comando específico para el despliegue