name: Flutter CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
      - pruebas
      - test
  pull_request:
    branches:
      - main
      - develop
      - pruebas
      - test
  workflow_dispatch: # Activación manual opcional

jobs:
  build:
    name: Build and Test Flutter MEF
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Configurar Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.6'

    # 3. Cachear las dependencias de Flutter
    - name: Cache Flutter Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-
    
    # Verify Flutter installation
    - name: Flutter Doctor
      run: flutter doctor

     # Install dependencies
    - name: Install dependencies
      run: flutter pub get
    
    # Notificaciones con Slack
    - name: Notify Slack 
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"¡Construcción y pruebas completadas con éxito!"}' \
        $SLACK_WEBHOOK_URL